from pathlib import Path
ROOT=Path(__file__).resolve().parent.parent
DESIGNS=[('d','Research index','トップビジュアルなし','概要・研究領域・成果から始まる、情報を優先した新案。画像は領域を見分けるための小さな補助に。'),('a','Sculptural art','立体アートと文字','立体アートと研究テーマを重ねる構成。紹介、成果、メンバー、交流・参加、アクセスを下部へ。'),('b','Photography','写真と文字','写真の境界に研究テーマを重ねる構成。写真とテーマが自動で切り替わります。'),('c','Generative field','点群アートと文字','動く点群と研究テーマを重ねる構成。共通の情報と導線で、ほかの案と比較できます。')]
STYLE='''@font-face{font-family:Outfit;src:url(assets/fonts/Outfit-wght.ttf);font-weight:100 900;font-display:swap}@font-face{font-family:MPlus;src:url(assets/fonts/MPLUS1-wght.ttf);font-weight:100 900;font-display:swap}*{box-sizing:border-box}body{margin:0;background:#f7f9fa;color:#263c46;font-family:Outfit,MPlus,sans-serif}a{color:inherit;text-decoration:none}main{max-width:1480px;margin:auto;padding:32px 34px 45px}h1{font-size:26px;font-weight:500;margin:0}h2{font-size:18px;font-weight:500;margin:0}p{font-size:13px;color:#637984;line-height:1.85}.top{display:flex;justify-content:space-between;align-items:center;gap:30px;margin-bottom:24px}.top p{max-width:920px;margin:9px 0 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:26px}.card{min-width:0;background:white;border:1px solid #dce5e8;border-radius:10px;overflow:hidden}.card.featured{border-color:#92b5ad}.card img{display:block;width:100%;height:auto}.image-link{display:block;border-bottom:1px solid #e8edf0}.copy{padding:21px 24px}.tag{display:inline-grid;place-items:center;min-width:30px;height:28px;font:15px Outfit,sans-serif;background:#edf2f5;border-radius:4px;margin-right:10px}.featured .tag{background:#e4f1eb;color:#29624e}.eyebrow{font:11px Outfit,sans-serif;letter-spacing:.05em;color:#758892;margin:0 0 9px}.badge{font:10px Outfit,sans-serif;background:#2f7463;color:white;padding:4px 7px;border-radius:3px;margin-left:10px;vertical-align:middle}.copy p:not(.eyebrow){margin:10px 0 13px}.actions{display:flex;gap:24px;flex-wrap:wrap}.actions a,.nav a{font-size:12px;min-height:44px;display:inline-flex;align-items:center;color:#326e72}.actions a:first-child{font-weight:550}.nav{display:flex;gap:24px}.pair{display:grid;grid-template-columns:minmax(0,1fr) 280px;gap:25px;align-items:start}.screen-label{font-size:12px;color:#617681;margin-bottom:9px;display:flex;justify-content:space-between}.screen{border:1px solid #dce5e8;background:#fff;border-radius:7px;overflow:hidden}.screen img{display:block;width:100%;height:auto}.review-note{font-size:12px;color:#657b88}.review-note a{text-decoration:underline;text-underline-offset:3px}a:focus-visible{outline:3px solid #30756e;outline-offset:4px}.page-note{margin-top:25px;font-size:12px}.page-note a{color:#326e72;text-decoration:underline;text-underline-offset:3px}@media(max-width:800px){main{padding:24px 18px}.grid{grid-template-columns:1fr}.top{display:block}.nav{margin-top:10px}.pair{grid-template-columns:1fr}.mobile{max-width:390px}.copy{padding:18px}h1{font-size:22px}}'''
def wrap(title,body):return f'<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><style>{STYLE}</style></head><body>{body}</body></html>'
cards=''
for code,eng,title,desc in DESIGNS:
 badge='<span class="badge">NEW</span>' if code=='d' else ''
 cards+=f'<article class="card {"featured" if code=="d" else ""}"><a class="image-link" href="takeda-kinetic-{code}.html"><img src="takeda-kinetic-{code}-pc.jpg" width="1440" height="900" alt="{code.upper()}案のPC画面"></a><div class="copy"><p class="eyebrow">{eng}</p><h2><span class="tag">{code.upper()}</span>{title}{badge}</h2><p>{desc}</p><div class="actions"><a href="takeda-kinetic-{code}.html">デザインを開く ↗</a><a href="takeda-kinetic-review-{code}.html">PC・スマホ比較 ↗</a><a href="takeda-kinetic-{code}-en.html">English ↗</a></div></div></article>'
 body=f'<main class="review"><div class="top"><div><h1><span class="tag">{code.upper()}</span>{title}</h1><p>{desc}</p></div><nav class="nav"><a href="index.html">4案を比較</a><a href="takeda-kinetic-{code}.html">デザインを開く ↗</a></nav></div><div class="pair"><div class="pc"><div class="screen-label"><span>PC / 1440 × 900</span></div><div class="screen"><img src="takeda-kinetic-{code}-pc.jpg" width="1440" height="900" alt="PC版"></div></div><div class="mobile"><div class="screen-label"><span>Mobile / 390 × 844</span></div><div class="screen"><img src="takeda-kinetic-{code}-mobile.jpg" width="390" height="844" alt="スマートフォン版"></div></div></div><p class="review-note">ここはスクリーンショットです。<a href="takeda-kinetic-{code}.html">実際のデザイン</a>ではページ下部まで確認できます。{ "大きなトップビジュアルを設けず、研究会の情報から始まる案です。" if code=="d" else "研究テーマは自動で切り替わります。" }</p></main>'
 (ROOT/f'takeda-kinetic-review-{code}.html').write_text(wrap(f'{code.upper()}案 / PC・スマホ比較',body))
body=f'<main><div class="top"><div><h1>Takeda Lab. / デザイン比較</h1><p>大きなトップビジュアルを置かないD案を追加しました。4案すべてに、研究領域・成果・メンバー・アクセスと、共同研究／交流・学生参加の2つの導線を反映しています。</p></div></div><div class="grid">{cards}</div><p class="page-note">画像と掲載内容の一部はプロトタイプ用の仮素材です。<a href="仮画像の生成記録.md">生成記録</a> · <a href="https://github.com/Hayato1031/tlab-design-test">GitHub</a></p></main>'
for name in ['index.html','takeda-kinetic-compare.html']:(ROOT/name).write_text(wrap('Takeda Lab. / 4案のデザイン比較',body))
print('Built comparison and review pages for 4 designs.')
